version: '3.8'

services:
  evolution-api:
    container_name: evolution-api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    environment:
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=postgresql://user:pass@host.docker.internal:5432/evolution_db
      - REDIS_ENABLED=false
      - SERVER_PORT=3000
      - SERVER_URL=http://localhost:3000

volumes:
  evolution_instances:

networks:
  evolution-net:
    external: true
